chainRpcs:
  - chainId: 31337
    rpcUrl: 'https://app.dev.portalgate.me:18545'

dbFilePath: 'darkSwap-dev.db'
bookNodeSocketUrl: 'wss://app.dev.portalgate.me:13001'
bookNodeApiUrl: 'https://app.dev.portalgate.me:13000'
